// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRitglUDt9qZKCwoUa7S-bDlak2YJ67L4',
    appId: '1:1088653673043:web:d665ae0bbb652111bffca6',
    messagingSenderId: '1088653673043',
    projectId: 'appprueba2-b28c1',
    authDomain: 'appprueba2-b28c1.firebaseapp.com',
    databaseURL: 'https://appprueba2-b28c1-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba2-b28c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc54EXPEngPU3fYFwAyPVgZzPoUTepFRU',
    appId: '1:1088653673043:android:2ed6d2c563d92e6ebffca6',
    messagingSenderId: '1088653673043',
    projectId: 'appprueba2-b28c1',
    databaseURL: 'https://appprueba2-b28c1-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba2-b28c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TM4uICV0hPA96HnlY974l9A-8BObQRc',
    appId: '1:1088653673043:ios:1479885e245cbef3bffca6',
    messagingSenderId: '1088653673043',
    projectId: 'appprueba2-b28c1',
    databaseURL: 'https://appprueba2-b28c1-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba2-b28c1.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3TM4uICV0hPA96HnlY974l9A-8BObQRc',
    appId: '1:1088653673043:ios:1479885e245cbef3bffca6',
    messagingSenderId: '1088653673043',
    projectId: 'appprueba2-b28c1',
    databaseURL: 'https://appprueba2-b28c1-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba2-b28c1.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRitglUDt9qZKCwoUa7S-bDlak2YJ67L4',
    appId: '1:1088653673043:web:cc267fc4359e9659bffca6',
    messagingSenderId: '1088653673043',
    projectId: 'appprueba2-b28c1',
    authDomain: 'appprueba2-b28c1.firebaseapp.com',
    databaseURL: 'https://appprueba2-b28c1-default-rtdb.firebaseio.com',
    storageBucket: 'appprueba2-b28c1.appspot.com',
  );

}